name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

env:
  # Deterministic build settings for releases
  SOURCE_DATE_EPOCH: 1734307200
  TZ: UTC
  LC_ALL: C
  LANG: C
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-release-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-release-${{ runner.os }}-
          gradle-${{ runner.os }}-
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'
        bundler-cache: true
        working-directory: .
    
    - name: Setup Ruby PATH
      run: |
        export PATH="$HOME/.rvm/gems/ruby-3.3.6/bin:$HOME/.rvm/rubies/ruby-3.3.6/bin:$PATH"
        echo "PATH=$PATH" >> $GITHUB_ENV
    
    - name: Install Fastlane dependencies
      run: |
        export PATH="$HOME/.rvm/gems/ruby-3.3.6/bin:$HOME/.rvm/rubies/ruby-3.3.6/bin:$PATH"
        bundle install
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3
    
    - name: Run tests before release
      run: |
        export PATH="$HOME/.rvm/gems/ruby-3.3.6/bin:$HOME/.rvm/rubies/ruby-3.3.6/bin:$PATH"
        bundle exec fastlane android test
    
    - name: Run lint checks before release
      run: |
        export PATH="$HOME/.rvm/gems/ruby-3.3.6/bin:$HOME/.rvm/rubies/ruby-3.3.6/bin:$PATH"
        bundle exec fastlane android lint
    
    - name: Build reproducible release APK
      run: |
        export PATH="$HOME/.rvm/gems/ruby-3.3.6/bin:$HOME/.rvm/rubies/ruby-3.3.6/bin:$PATH"
        bundle exec fastlane android reproducible
    
    - name: Verify reproducible build
      run: |
        export PATH="$HOME/.rvm/gems/ruby-3.3.6/bin:$HOME/.rvm/rubies/ruby-3.3.6/bin:$PATH"
        bundle exec fastlane android verify_reproducible
    
    - name: Prepare F-Droid metadata
      run: |
        export PATH="$HOME/.rvm/gems/ruby-3.3.6/bin:$HOME/.rvm/rubies/ruby-3.3.6/bin:$PATH"
        bundle exec fastlane android prepare_fdroid_metadata
    
    - name: Generate release checksums
      run: |
        cd app/build/outputs/apk/release/
        sha256sum *.apk > checksums.txt
        cat checksums.txt
    
    - name: Extract version from tag
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Release version: $VERSION"
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: DarklakeWallet ${{ steps.version.outputs.version }}
        body: |
          ## DarklakeWallet ${{ steps.version.outputs.version }}
          
          ### 📱 Downloads
          - `app-release-unsigned.apk` - Unsigned APK for F-Droid
          - `checksums.txt` - SHA256 checksums for verification
          
          ### 🔒 Security
          This release is built reproducibly. You can verify the build by:
          1. Checking out this exact commit
          2. Building with the same environment settings
          3. Comparing checksums
          
          ### ✅ F-Droid Ready
          This APK is unsigned and ready for F-Droid inclusion.
          
          ### 🧪 Testing
          All tests and lint checks have passed before this release.
          
          ---
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.version.outputs.version }}
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}
    
    - name: Upload unsigned APK to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: app-release-unsigned.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload checksums to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain
    
    - name: Upload F-Droid metadata
      uses: actions/upload-artifact@v4
      with:
        name: fdroid-metadata-${{ steps.version.outputs.version }}
        path: metadata/
        retention-days: 365
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts-${{ steps.version.outputs.version }}
        path: |
          app/build/outputs/apk/release/
          build-info.json
          verification-builds/
        retention-days: 365